# Generated by Django 5.0.6 on 2024-07-09 00:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consignment_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addconsignment',
            name='cgst',
            field=models.IntegerField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='addconsignment',
            name='gst',
            field=models.IntegerField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='addconsignment',
            name='sgst',
            field=models.IntegerField(max_length=50, null=True),
        ),
    ]
