# Generated by Django 5.0.6 on 2024-07-09 01:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consignment_app', '0003_alter_addconsignment_cgst_alter_addconsignment_sgst'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addconsignment',
            name='desc_product',
            field=models.CharField(max_length=150, null=True),
        ),
    ]
