# Generated by Django 5.0.6 on 2024-07-10 00:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consignment_app', '0005_addconsignment_consignment_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='addconsignment',
            name='sender_GST',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='addconsignment',
            name='sender_company',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
